// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apulorzqemmioigdovlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdWxvcnpxZW1taW9pZ2Rvdmx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Njc5NzksImV4cCI6MjA3MjM0Mzk3OX0.ljAYu86fOcw1FgXGycFyrQU9KfAUrK6bIeBsFKBViD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});